spring.datasource.url=jdbc:postgresql://ec2-34-235-31-124.compute-1.amazonaws.com:5432/d37p20rmru6shb
spring.datasource.username=uvbwvxqfnjkgrh
spring.datasource.password=175231d1ff84cbc12753a9a3b17ecaa2a6be1212e4bfde11df464fe9edc63ce7
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
