spring.datasource.url=jdbc:postgresql://ec2-3-223-169-166.compute-1.amazonaws.com:5432/da938m8j9bmuq4
spring.datasource.username=pbnzpprmplylfw
spring.datasource.password=cb06c27fdd3e1f17c627390117e32219b43d1097819aefbc0adc394a02025e61
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
